chat/urls.py
from django.urls import path, re_path

from . import views


app_name = 'chat'

urlpatterns = [
    path('', views.lobby, name='lobby'),
    path('entrance', views.entrance, name='entrance'),
    path('room/<str:room_name>/', views.room, name='room'),
    path('new/', views.create_room, name='new_room'),
    path('search', views.search_room, name='search_room'),
    re_path(r'^members/(?:(?P<room_name>\w+)/)?$', views.list_members, name='members'),
]

websocket_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
]

chat/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse
from django.http.response import JsonResponse
from django.views.decorators.http import require_GET, require_POST

from .events import Events
from .utils import nickname_required
from .services.chat_service import Room, Chat
from .services.errors import DuplicatedRoomNameError, RoomDoesNotExistError

chat_service = Chat()


def lobby(request):
    room_list = chat_service.list_rooms()
    return render(request, 'chat/lobby.html', {
        'room_list': room_list,
    })


@nickname_required
def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name': room_name,
        'events': {
            'CHAT': Events.CHAT.value,
            'NEW_USER': Events.NEW_USER.value,
            'NOTIFICATION': Events.NOTIFICATION.value,
        },
    })


def entrance(request):
    next = request.GET['next']
    return render(request, 'chat/entrance.html', {
        'next': next,
    })


@require_POST
def create_room(request):
    room_name = json.loads(request.body.decode('utf-8'))['name']
    try:
        room = Room(room_name)
        chat_service.create_room(room)
    except DuplicatedRoomNameError:
        return HttpResponse(status=400)
    return HttpResponse(status=201)


@require_GET
def search_room(request):
    keyword = request.GET['keyword']
    rooms = chat_service.list_rooms_by_keyword(keyword)
    response = {
        'rooms': rooms
    }
    return JsonResponse(response, status=200)


@require_GET
def list_members(request, room_name=None):
    try:
        if room_name:
            member_list = chat_service.list_members_in_room(room_name)
        else:
            member_list = chat_service.map_rooms_with_member_names()
        response = {
            'members': member_list
        }
        return JsonResponse(response, status=200)
    except RoomDoesNotExistError:
        return HttpResponse(status=400)

templates/chat/entrance.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}Chat Room Entrance{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/nickname.css' %}">
{% endblock %}

{% block contents %}
<div class="nicknameSubmitContainer">
    <form class="form-inline" method="POST" action="{{ next }}" id="username-form">
        {% csrf_token %}
        <div class="form-group"><input class="form-control" type="text" name="nickname" placeholder="Set Your Nickname"></div>
        <div class="form-group"><button class="btn btn-primary" type="submit">Start Chat </button></div>
    </form>
</div>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript" src="{% static 'js/nickname.js' %}"></script>
{% endblock %}

templates/chat/lobby.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}Chat Lobby{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/lobby.css' %}">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <!-- start:lobby -->
            <div class="box">
                <div class="chat-room">
                    <!-- start:aside lobby kiri -->
                    <!-- 왼쪽 사이드바 -->
                    <aside class="kiri-side">
                        <div class="user-head">
                            <i class="fa fa-comments-o"></i>
                            <h1 id="chat-title">Chat Lobby</h1>
                        </div>
                        <ul class="chat-list">
                            <li class="active">
                                <h4>
                                    <i class="fa fa-list"></i>
                                    Active Members in Lobby
                                    </h2>
                            </li>
                            <ul class="chat-list" id="lobbyMember-list"></ul>
                        </ul>
                    </aside>
                    <!-- end:aside lobby kiri -->
                    <!-- start:aside lobby tengah -->
                    <!-- 중간 채팅방 리스트 -->
                    <aside class="tengah-side">
                        <div class="chat-room-head">
                        </div>
                        <div class="room-desk">
                            {% csrf_token %}
                            <h4 class="pull-left">open rooms</h4>
                            <button class="custom-btn pull-right btn" data-toggle="modal" data-target="#submitModal">+
                                Create Room</button>
                            {% for room in room_list %}
                            <div class="room-box">
                                <div class="roomTitle-wrapper">
                                    <h5>{{ room }}</h5>
                                    <p>
                                        <span class="text-muted">Members :</span>
                                        <span id="{{ room }}-members-container"></span>
                                    </p>
                                </div>
                                <a href="{% url 'chat:room' room_name=room %}">
                                    <button class="custom-btn-white pull-right btn btn-sm">Join Room</button>
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                    </aside>
                    <!-- end:aside lobby tengah -->
                    <!-- start:aside lobby kanan -->
                    <!-- 오른쪽 사이드바 -->
                    <aside class="kanan-side">
                        <div class="user-head">
                        </div>
                        <div class="invite-row">
                            <div class="pull-right position" id="room-search-form">
                                <input type="text" placeholder="Search chat room" class="form-control search-btn"
                                    id="room-search-input">
                                <button class="chat-tools btn btn-default custom-btn" id="room-search-btn"><i
                                        class="fa fa-search"></i></button>
                            </div>
                        </div>
                        <ul class="chat-available-user" id="room-search-result-list">
                        </ul>
                    </aside>
                    <!-- end:aside lobby kanan -->
                </div>
            </div>
            <!-- end:lobby -->
        </div>
    </div>
</div>
{% include 'components/submitModal.html' %}
{% endblock %}

{% block scripts %}
{{ block.super }}
<script type="module" src="{% static 'js/initLobby.js' %}"></script>
{% endblock %}

templates/chat/room.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}Chat Room{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/room.css' %}">
{% endblock %}

{% block contents %}
{{ room_name|json_script:"room-name" }}
{{ events|json_script:"events" }}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center no-margin">
            <div class="col-md-6">
                <div class="card card-bordered">
                    <div class="card-header">
                        <a href="{% url 'chat:lobby' %}"><i class="fa fa-chevron-left" id="backBtn"></i></a>
                        <h4 class="card-title"><strong>{{ room_name }}</strong></h4>
                        <div class="btn btn-sm" id="nickname-btn"></div>
                    </div>
                    <div class="ps-container ps-theme-default ps-active-y" id="messageBox"
                        style="overflow-y: scroll !important; height:400px !important;">
                        <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;">
                            <div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div>
                        </div>
                        <div class="ps-scrollbar-y-rail" style="top: 0px; height: 0px; right: 2px;">
                            <div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 2px;"></div>
                        </div>
                    </div>
                    <div class="publisher bt-1 border-light">
                        <input id="chat-message-input" class="publisher-input" type="text"
                            placeholder="Write a message">
                        <input id="chat-message-submit" class="publisher-btn btn custom-btn" type="button" value="Send">
                    </div>
                    <div class="memberList-container">
                        <p class="memberList-header">Joined Members</p>
                        <ul id="memberList"></ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="notificationBox"></div>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script type="module" src="{% static 'js/initChatRoom.js' %}"></script>
{% endblock %}

templates/components/submitModal.html
<div class="modal fade" id="submitModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold" id="form-title">Create Chat Room</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3">
                <div class="md-form mb-5" id="submitForm-wrapper">
                    <p data-error="wrong" data-success="right">Enter your room name</p>
                    <input type="text" id="room-name-input" class="form-control validate"
                        placeholder="Up to 20 characters">
                </div>
            </div>
            <div class="modal-footer d-flex justify-content-center">
                <input type="button" class="btn custom-btn" id="room-name-submit" data-dismiss="modal" value="Create">
            </div>
        </div>
    </div>
</div>

templates/layouts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  {% block styles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'css/button.css' %}">
  <link rel="stylesheet" href="{% static 'css/form.css' %}">
  {% endblock %}
</head>

<body>
  <main id="root">
    {% block contents %}{% endblock %}
  </main>
  {% block scripts %}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  {% endblock %}
</body>

</html>